### ISSUE TITLE
Support for Symfony 7

### ISSUE THREAD

**Issue by back-2-95** [dunglas/doctrine-json-odm#129]
Symfony 7 will be released at the end of the next month. Could there be a pre-release allowing Symfony 7 install?

https://symfony.com/blog/prepare-yourself-for-symfony-6-4-and-symfony-7-0

**Comment by dunglas** [comment]
PR welcome!

**Comment by back-2-95** [comment]
@dunglas things seems to work as before for me in existing project. See #130
