### ISSUE TITLE
Create a new release for Symfony 7?

### ISSUE THREAD

**Issue by back-2-95** [dunglas/doctrine-json-odm#132]
As #130 was merged and now Symfony 7 has been released, maybe there could be a new release for this library?

**Comment by back-2-95** [comment]
Ah there is some tasks going on in #131 still...

**Comment by norkunas** [comment]
ping @dunglas :pray:

**Comment by dunglas** [comment]
Done! https://github.com/dunglas/doctrine-json-odm/releases/tag/v1.4.0

Thanks for your patience.
