### ISSUE TITLE
DBAL master implemented MySQL-JSON now

### ISSUE THREAD

**Issue by spackmat** [dunglas/doctrine-json-odm#20]
The README.md mentioned https://github.com/doctrine/dbal/pull/2266 as a requirement for MySQL-support. This PR was dropped in favor of https://github.com/doctrine/dbal/pull/2653, which was merged to master three days ago. Hooray.

Does that mean, this bundle here is now ready for use with the master branch of Doctine DBAL? Or does it need any changes to support it?

Greets, spackmat

**Comment by dunglas** [comment]
@spackmat, yes it should work without any change (I've not tested this right now).
It would be nice to add a functional test with MySQL (we already have one for Postgres) and update the README.
