### ISSUE TITLE
Deprecation Warning with doctrine/dbal 2.6.x-dev

### ISSUE THREAD

**Issue by spackmat** [dunglas/doctrine-json-odm#22]
Hi, I'm using this bundle with the master/2.6.x-dev branch of Doctrine (which is needed at the moment to support MySQL natibe JSON). I get this deprecation warning:

> User Deprecated: The "Dunglas\DoctrineJsonOdm\Type\JsonDocumentType" class extends "Doctrine\DBAL\Types\JsonArrayType" that is deprecated Use JsonType instead

This raises the question, if Doctrine implements native JSON by itself, dropping the old JSON-array-type in favor of it? Will this bundle then be needed at all? Would be great!

Greets,
spackmat

**Comment by dunglas** [comment]
Yes the bundle is still needed, the main benefit of this bundle is its ability to store complex types (objects for instance). The native JSON type can just store primitive types, array and anonymous objects.

The deprecation must be fixed.
