### ISSUE TITLE
Use this package without Symfony

### ISSUE THREAD

**Issue by Ducatel** [dunglas/doctrine-json-odm#34]
Hi,

There is a way to use this package in doctrine 2 without Symfony ?

From the readme
> Doctrine JSON ODM can also be used standalone, without any framework, but the documentation hasn't been redacted yet (PRs welcome!).

So seems to be possible but I cannot found any resource about that.

Can you help me for that ?
Thanks in advance ;)

**Comment by dunglas** [comment]
You need to:

1. Create an instance of the Symfony Serializer component, and register the normalizer provided by this bundle. Here is the Symfony DIC config, but you can just use plain `new`: https://github.com/dunglas/doctrine-json-odm/blob/master/src/Bundle/Resources/config/services.xml
2. Just use the DBAL type directly: https://github.com/dunglas/doctrine-json-odm/blob/master/src/Type/JsonDocumentType.php and pass the normalizer calling its `setSerializer` method.

If you manage to get this working, would you mind opening a PR to add instructions to the README file?

**Comment by Ducatel** [comment]
Ok, so I'm absolutely not a symfony user so I did understand how use the DIC.

What I have done now
```php
//bootstrap.php
require_once __DIR__."/../vendor/autoload.php";

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Dunglas\DoctrineJsonOdm\Type\JsonDocumentType;

if (!Type::hasType('json_document')) {
    Type::addType('json_document', JsonDocumentType::class);
    $type = Type::getType('json_document');

    $serializer = new Symfony\Component\Serializer\Serializer(['dunglas_doctrine_json_odm.serializer']); // I don't know if that is good .....

    $type->setSerializer($serializer);
}


$isDevMode = true;
$config = Setup::createAnnotationMetadataConfiguration(array(__DIR__ . "/../src"), $isDevMode);
$conn = [
    'dbname' => 'test',
    'user' => '',
    'password' => '',
    'host' => 'db',
    'driver' => 'pdo_mysql'
];

$entityManager = EntityManager::create($conn, $config);
return $entityManager;
```

But when I try to store an object I have this error 
```

Fatal error: Uncaught Symfony\Component\Serializer\Exception\NotEncodableValueException: Serialization for the format json is not supported in /var/www/html/vendor/symfony/serializer/Serializer.php on line 112

Symfony\Component\Serializer\Exception\NotEncodableValueException: Serialization for the format json is not supported in /var/www/html/vendor/symfony/serializer/Serializer.php on line 112
```

So seems to not understand the `json_document` type (but my db contains the column with the type `json`)


Ps: What is the different between this package and the native support of json by doctrine ?
Can will made a `findBy` with a json condition ? or I will must use a native query ?

Thanks ;)

**Comment by dunglas** [comment]
Can you try this change?

```php
//bootstrap.php
require_once __DIR__.'/../vendor/autoload.php';

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Dunglas\DoctrineJsonOdm\Type\JsonDocumentType;

if (!Type::hasType('json_document')) {
    Type::addType('json_document', JsonDocumentType::class);
    $type = Type::getType('json_document');

    $serializer = new \Symfony\Component\Serializer\Serializer([
        new \Dunglas\DoctrineJsonOdm\Normalizer\ObjectNormalizer(
            new \Symfony\Component\Serializer\Normalizer\ObjectNormalizer()
        )
    ]);

    $type->setSerializer($serializer);
}


$isDevMode = true;
$config = Setup::createAnnotationMetadataConfiguration(array(__DIR__ . "/../src"), $isDevMode);
$conn = [
    'dbname' => 'test',
    'user' => '',
    'password' => '',
    'host' => 'db',
    'driver' => 'pdo_mysql'
];

$entityManager = EntityManager::create($conn, $config);
return $entityManager;
```

If you want to leverage advanced features of the Symfony's Object Normalizer, you'll need some more dependencies: https://symfony.com/doc/current/components/serializer.html#attributes-groups

**Comment by Ducatel** [comment]
Ok so now it's working, thanks ;)
(A dependency on `symfony/property-access` is missing ;) , I will put it in PR when I finish my sample)

So I can store my object (with one `json_document` column inside) in MySQL DB but I cannot find how make request on this field.

I'm trying to do
```
$rsm = new ResultSetMapping();
$query = $entityManager->createNativeQuery('select * from my_table where json_extract(jsonData, "$.test.key1")= "value1"', $rsm); // the column jsonData contains {"test": {"key1": "value1"}}
var_dump($query->getResult());
```

This query works in MySQL directly but not througth Doctrine.
Do you know why ?
Is it possible to not use a native query ?

And also, What is the different between this package and the native support of json by doctrine ?

Thanks for your help ;)

**Comment by dunglas** [comment]
> So I can store my object (with one json_document column inside) in MySQL DB but I cannot find how make request on this field without using native query. It's possible ?

For now you need to use a native query (or to extend DQL), indeed.

> And also, What is the different between this package and the native support of json by doctrine2 ?

When deserializing, it preserves PHP types. Doctrine native type will just create associative arrays or `stdClass`es.

**Comment by Ducatel** [comment]
Ok, thanks for your help ;)
