### ISSUE TITLE
Can't get it working with Sf4 

### ISSUE THREAD

**Issue by alOneh** [dunglas/doctrine-json-odm#36]
First, I wish you a happy new year !

I try to setup the bundle on a Symfony 4 project and I have a random unexpected error : 
`An instance of "Symfony\Component\Serializer\SerializerInterface" must be available. Call the "setSerializer" method.`

For more context, I use API Platform and try to persist an entity with a value object on it in an Action
Sometimes it works, sometimes not... When I try to debug the `DunglasDoctrineJsonOdmBundle` class in the `boot` method, I can see the right instance when dumping the `JsonDocumentType::getSerializer` method.

**Comment by Toflar** [comment]
I guess this is resolved in the meantime? At least I can use it with Flex just fine.
Let me know if the issue must be reopened.
