### ISSUE TITLE
de-serialized entities have id: NULL unless setId($id) method created

### ISSUE THREAD

**Issue by epoplive** [dunglas/doctrine-json-odm#37]
I'm trying to use this, but I'm finding that all of my serialized doctrine entities have an id of NULL unless I create a setId($id) method in each entity.

**Comment by Toflar** [comment]
Is this issue still relevant or has it been resolved in the meantime?

**Comment by TonyBogdanov** [comment]
It is still relevant, but the clue is it only happens if the class has a `getId` method, which leads me to believe it goes into a *getter* / *setter* mode. So, for anyone experiencing this, either use both `getId()`, `setId()`, or neither, don't declare just one of them.
