### ISSUE TITLE
Doctrine seems to not see changes in objects kept in jsonb fields.

### ISSUE THREAD

**Issue by anonim1133** [dunglas/doctrine-json-odm#38]
Doctrine entity named A has field "b"(jsonb) which contains object B. B has two fields "c and d", both strings.

When I update field c of b
`A->b->c = new value
entity manager -> flush`

Nothing is saved to database. I expected it to update field c of object b in database, but old value remains.

Is that anticipated behaviour? Is that my error, doctrine, or this bundle?

When I put new object to filed b, then changes are registered and field is updated.

I've hope that i was clear enough.

**Comment by pbowyer** [comment]
Duplicate of https://github.com/dunglas/doctrine-json-odm/issues/21 ?

**Comment by anonim1133** [comment]
It seems so.
