### ISSUE TITLE
Using without Symphony - no setSerializer function in Type class?

### ISSUE THREAD

**Issue by zedle** [dunglas/doctrine-json-odm#42]
Using Doctrine ORM / DBAL >= 2.6.. Any idea how to get this working without Symphony? The setSerializer function seems to be missing.

**Comment by dunglas** [comment]
Did you tried https://github.com/dunglas/doctrine-json-odm#install?
Can you copy the stack trace?

**Comment by IsThatYouDaz** [comment]
I just had this same problem. I solved it by installing the symfony/property-access component via composer.

**Comment by Toflar** [comment]
Both of these libraries are dependencies so I guess this was rather some local issue.
Let me know if I need to reopen.
