### ISSUE TITLE
when i save data i'm getting extra slashes in symfony4

### ISSUE THREAD

**Issue by tenken** [dunglas/doctrine-json-odm#55]
If I create some json, for example:
```json
{
  "date": "2018-10-05 20:38:37",
  "data_retention_policy": "test",
  "error_code": null,
  "error_message": null
}
```

using the following code:
```php
$request_type = 'createNewUnitTestRequestSetMetadata';
$wrs_json_metadata = WebextractMetadata::$request_type()->getJSON();
echo "wrs_json_metadata is: " . $wrs_json_metadata;
# yields => {"date":"2018-10-05 20:38:37","data_retention_policy":"test","error_code":null,"error_message":null}
$wrs = new WebextractRequestSet();
$date = new \DateTime('@' . strtotime(json_decode($wrs_json_metadata)->date));
$wrs->setDateRequested($date);
$wrs->setMetadata($wrs_json_metadata);
$em->persist($wrs);
$em->flush();
```
When I look in the database the json values are stored as:

```txt
mysql> select metadata from webextract_request_set where id = 5\G;
*************************** 1. row ***************************
metadata: "{\"date\":\"2018-10-05 20:38:37\",\"data_retention_policy\":\"test\",\"error_code\":null,\"error_message\":null}"
1 row in set (0.00 sec)
```

Am I doing something wrong here? I simply `composer require dunglas/doctrine-json-odm` and then used `php bin/console entity:create` and created the metadata column as a `json_document` field type.

As you may note i'm trying to store the json string to the Entity, should I be trying to store the json object and not a string representation of it?

Thanks for your time. -David

**Comment by tenken** [comment]
For completeness, my custom `getJSON()` function looks like the following:

```php
  // properties here is simply a php array of key/value pairs.
  public function getJSON() {
    if (!is_null($this->api_request_properties)) {
      return json_encode($this->api_request_properties);
    }
    return json_encode($this->web_request_properties);
  }
```

**Comment by tenken** [comment]
I dont have a solution persay, but `make:entity` with the field type `json_document` yields an annotation such as:

### Initial annotation created by make:entity
```php
  /**
   * @ORM\Column(type="json_document")
   */
  private $data;

  /**
   * @ORM\Column(type="json_document")
   */
  private $metadata;
```
I have edited this value to make it more simple and now the field is stored without the outermost quotes and is not escaping key/value string quotes within the json document.

#### Revised:
```php
  /**
   * @ORM\Column(type="string")
   */
  private $data;

  /**
   * @ORM\Column(type="string")
   */
  private $metadata;
```

Anyways I hope this information is helpful. If I can be of anymore assistance please let me know and I will get back to you.

**Comment by Toflar** [comment]
I fail to understand the issue here. Can you describe what you expect?
