### ISSUE TITLE
Caching serializer

### ISSUE THREAD

**Issue by Siregacvek** [dunglas/doctrine-json-odm#59]
Hello!

I would to like to know is there any reason why this serializer doesn't implement `CacheableSupportsMethodInterface`?

Thanks.

**Comment by Toflar** [comment]
I think there‘s not :) PR welcome!

**Comment by Siregacvek** [comment]
Ok, will do in a few days.

**Comment by Toflar** [comment]
Closed in favor of https://github.com/dunglas/doctrine-json-odm/pull/61
