### ISSUE TITLE
Persisting ArrayCollection

### ISSUE THREAD

**Issue by sergiolatostadora** [dunglas/doctrine-json-odm#62]
It's possible to persist an arrayCollection? I'm trying to persist with xml with:

        <field name="priceCollection" column="priceCollection" type="json_document"/>

My database is MariaDB 10.4 I'm using migrations.When I persist I only see void elements

{"#type":"App\\Domain\\Shared\\Price\\PriceCollection","keys":[0],"values":[{"#type":"App\\Domain\\Shared\\Price\\Price"}],"empty":false,"iterator":{"#type":"ArrayIterator","arrayCopy":[{"#type":"App\\Domain\\Shared\\Price\\Price"}],"flags":0}}

**Comment by Toflar** [comment]
I cannot tell you by heart but maybe this points you into the right direction to continue your debugging session: The type uses an instance of the Symfony serializer. If it contains a normalizer that is able to handle `instanceof ArrayCollection` it should work. You probably need to register it, also see https://github.com/dunglas/doctrine-json-odm#faq (`How can I add additional normalizers?`).

**Comment by sergiolatostadora** [comment]
I tried with a collection normalizer but I'm not able to persist data, I'm a little newbie with normalizers and doctrine

**Comment by sergiolatostadora** [comment]
I made it work injecting propertyNormalizer to Dunglas Object Normalizer via services.yml

**Comment by sergiolatostadora** [comment]
You think is very bad in performance use propertyNormalizer vs ObjectNormalizer? thx

**Comment by Toflar** [comment]
Not really no, the more normalizers you register, the more the serializer calls to ask them whether they support normalizing the value but for the most part that should not be too bad in performance.
