### ISSUE TITLE
it is better to use ODM metadata instead of serializer

### ISSUE THREAD

**Issue by videni** [dunglas/doctrine-json-odm#68]
I think it is better to use ODM  for jsonb  instead of serializer, for example, 
```
  /**
   * Can contain anything (array, objects, nested objects...).
   *
   * @ORM\Column(type="json_document", options={"jsonb": true, "entity"="App\Entity\A_POLO"})
   */
  public $misc;
```

 <document name="App\Entity\A_POLO"
   >
       <field name="name" column="name" type="string" length="255" />
        <field name="createdAt" column="created_at" type="datetime" nullable="true" >
        </field>
        <field name="updatedAt" column="updated_at" type="datetime" nullable="true">
        </field>
</document>

**Comment by Toflar** [comment]
I fail to understand this issue. @dunglas maybe? 😄
