### ISSUE TITLE
Can I use this with Doctrine 2.5 and Zend Framework? setSerializer issue

### ISSUE THREAD

**Issue by siedovolosyi** [dunglas/doctrine-json-odm#76]
Can I use this with Doctrine 2.5 and Zend Framework?
At the moment I have problem with
`Type::getType('json_document')->setSerializer(
        new Serializer([new ObjectNormalizer(new BaseObjectNormalizer())], [new JsonEncoder()])
    );`
because Type doesn't have **setSerializer** method.

**Comment by bpolaszek** [comment]
Have you done this first? This should override the original `json_document` type.

```php
Type::addType('json_document', \Dunglas\DoctrineJsonOdm\Type\JsonDocumentType::class);
```

**Comment by siedovolosyi** [comment]
Hi, thanks for answer.
I am use config file doctrine.global.php
`return [
    'doctrine' => [
        'connection' => [
            'orm_default' => [
            ...
            'doctrineTypeMappings' => [
                    'json_document' => 'json_document'
                ],
            ],
        'configuration' => [
             'orm_default' => [
                 ...
                 'types' =>[
                    'json_document' => JsonDocumentType::class
                ]
            ],
`
After schema update I got (DC2Type:json_document)'. All ok. But could you help, how I can set:
`->setSerializer(
            new Serializer([new ObjectNormalizer(new BaseObjectNormalizer())], [new JsonEncoder()])   )`
Can I use it here?
`class Module implements AutoloaderProviderInterface, ConfigProviderInterface
{
    /**
     * @param MvcEvent $e
     */
    public function onBootstrap(MvcEvent $e)
    {
        if (!Type::hasType('json_document')) {
            Type::addType('json_document', JsonDocumentType::class);
            /** @var \Dunglas\DoctrineJsonOdm\Type\JsonDocumentType $jsonDocument */
            $jsonDocument = Type::getType('json_document');
            $jsonDocument->setSerializer(
                new Serializer([new ObjectNormalizer(new BaseObjectNormalizer())], [new JsonEncoder()])
            );
        }
        $eventManager        = $e->getApplication()->getEventManager();
        $moduleRouteListener = new ModuleRouteListener();
        $moduleRouteListener->attach($eventManager);

        $eventManager->attachAggregate(new \Common\Listener\ApiErrorListener());
        $eventManager->attachAggregate(new \Common\Listener\ApiWorkoutListener());
        $eventManager->attachAggregate(new \Common\Listener\RoutingListener());

        ServiceLocator::setInstance($e->getApplication()->getServiceManager());
    }`

**Comment by bpolaszek** [comment]
Try removing the `Type::hasType('json_document')` condition because Doctrine already has this type (the goal is to override it).

**Comment by bpolaszek** [comment]
My bad, I was sure of something that was actually wrong. Doctrine natively has `json` (and `json_array` in older versions), not `json_document`. 

Your setup looks good at first glance. What exception is thrown?
